# 注意：Windows路径必须使用双反斜杠或正斜杠
[cache]
# 使用本地磁盘缓存（显式指定路径）
type = "local"
dir = "D:/Projects/rust/.sccache"  # 或 "D:\\Projects\\rust\\.sccache"

# 缓存大小限制（单位：GB）
max_size = 10

# Windows特有设置
[cache.local]
# 处理Windows路径差异
slash_convert = "forward"  # 将反斜杠转为正斜杠
ignore_case = true         # 忽略路径大小写

[build]
# 强制缓存通常不缓存的内容
cache_compiler_outputs = true
cache_script_outputs = true
disable_mlock = true       # Windows下禁用内存锁定

[compiler]
# 允许增量编译缓存
incremental = true

# 处理缺失输入文件的问题
ignore_missing_includes = false  # 设为true可忽略，但可能掩盖真实问题

[compiler.rust]
# 允许所有crate类型缓存
crate_types_allowed = [
    "bin", "lib", "dylib", 
    "staticlib", "cdylib", 
    "rlib", "proc-macro"
]

# 特殊环境变量处理
[env]
# 忽略可能影响缓存键的变量
ignored_env_vars = [
    "CARGO", "PATH", "USERPROFILE",
    "HOMEDRIVE", "HOMEPATH", "SystemRoot"
]

# 分布式编译配置（如需）
#[dist]
# scheduler = "http://scheduler:10600"
# toolchains = ["stable-x86_64-pc-windows-msvc"]